services:
  # 游릭 Editor principal n8n
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=${URL}
      - TZ=${TIMEZONE}
      - GENERIC_TIMEZONE=${TIMEZONE}
      # Corre칞칫es de proxy / rate limit
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_TRUSTED_PROXIES=0.0.0.0/0
      - N8N_RATE_LIMIT_ENABLED=true
      # Seguran칞a recomendada
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    depends_on:
      - postgres
    networks:
      - n8n-network
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678" # Editor do n8n

  # 游릭 Banco PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network

  # 游릭 Redis (mem칩ria para n8n e WAHA)
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - n8n-network
    volumes:
      - redis_data:/data

  # 游릭 WAHA (WhatsApp API Headless)
  waha:
    container_name: waha
    image: devlikeapro/waha:latest
    restart: unless-stopped
    environment:
      - WAHA_LICENSE=free
      - WAHA_LOG_LEVEL=debug
      - WAHA_SERVER_PORT=3000
      - WAHA_CHROMIUM_PATH=/usr/bin/google-chrome
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_REDIS_URL=redis://redis:6379
      - TZ=${TIMEZONE}
    ports:
      - "3000:3000"
    networks:
      - n8n-network
    volumes:
      - waha_data:/app/data

  # 游릭 Cloudflared (Quick Tunnel)
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiMTkxMDg5MmU5ZDMyZDBhNTA1NmRiZTQ0NjBkZWEwYzEiLCJ0IjoiNDgxMTNhMDMtNTEwYy00MTg4LTlmNTgtZGIwZTg2NjI5MzM5IiwicyI6IlpqYzNOMlJpTVRZdE9HRmxZaTAwWWpBNUxUZ3pNR0V0T1dRNVptWm1ZV0ppTm1NMSJ9
    restart: unless-stopped
    networks:
      - n8n-network

# 游댳 Volumes persistentes
volumes:
  n8n_data:
  postgres_data:
  redis_data:
  waha_data:

# 游댳 Rede customizada
networks:
  n8n-network:
    driver: bridge


